# Generated by Django 4.1.7 on 2023-09-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elearn', '0002_alter_categories_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('fee', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('module', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.categories')),
            ],
        ),
    ]
